/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class CommandType.
* @enum {}
* @readonly
*/
export default class CommandType {
        /**
         * value: "PlainText"
         * @const
         */
        PlainText = "PlainText";

        /**
         * value: "Json"
         * @const
         */
        Json = "Json";


    /**
    * Returns a <code>CommandType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/CommandType} The enum <code>CommandType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}
