/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class CommandPropertyType.
* @enum {}
* @readonly
*/
export default class CommandPropertyType {
        /**
         * value: "Default"
         * @const
         */
        Default = "Default";

        /**
         * value: "Integer"
         * @const
         */
        Integer = "Integer";

        /**
         * value: "Decimal"
         * @const
         */
        Decimal = "Decimal";

        /**
         * value: "Float"
         * @const
         */
        Float = "Float";

        /**
         * value: "DateAndTime"
         * @const
         */
        DateAndTime = "DateAndTime";

        /**
         * value: "Collection"
         * @const
         */
        Collection = "Collection";


    /**
    * Returns a <code>CommandPropertyType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/CommandPropertyType} The enum <code>CommandPropertyType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}
