/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ComputeExpressionType.
* @enum {}
* @readonly
*/
export default class ComputeExpressionType {
        /**
         * value: "Generic"
         * @const
         */
        Generic = "Generic";

        /**
         * value: "Raw"
         * @const
         */
        Raw = "Raw";

        /**
         * value: "Computed"
         * @const
         */
        Computed = "Computed";

        /**
         * value: "Analysed"
         * @const
         */
        Analysed = "Analysed";


    /**
    * Returns a <code>ComputeExpressionType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ComputeExpressionType} The enum <code>ComputeExpressionType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}
