/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ComputeExpressionViewModel from './ComputeExpressionViewModel';
import ComputeValueViewModel from './ComputeValueViewModel';
import SubComputeViewModel from './SubComputeViewModel';

/**
* The ComputeViewModel model module.
* @module model/ComputeViewModel
* @version 5
*/
export default class ComputeViewModel {
    /**
    * Constructs a new <code>ComputeViewModel</code>.
    * @alias module:model/ComputeViewModel
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ComputeViewModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ComputeViewModel} obj Optional instance to populate.
    * @return {module:model/ComputeViewModel} The populated <code>ComputeViewModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ComputeViewModel();
                        
            
            if (data.hasOwnProperty('guid')) {
                obj['guid'] = ApiClient.convertToType(data['guid'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('formula')) {
                obj['formula'] = ApiClient.convertToType(data['formula'], 'String');
            }
            if (data.hasOwnProperty('delay')) {
                obj['delay'] = ApiClient.convertToType(data['delay'], 'Number');
            }
            if (data.hasOwnProperty('failCount')) {
                obj['failCount'] = ApiClient.convertToType(data['failCount'], 'Number');
            }
            if (data.hasOwnProperty('isEnabled')) {
                obj['isEnabled'] = ApiClient.convertToType(data['isEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('expressions')) {
                obj['expressions'] = ApiClient.convertToType(data['expressions'], [ComputeExpressionViewModel]);
            }
            if (data.hasOwnProperty('childComputes')) {
                obj['childComputes'] = ApiClient.convertToType(data['childComputes'], [SubComputeViewModel]);
            }
            if (data.hasOwnProperty('parentComputes')) {
                obj['parentComputes'] = ApiClient.convertToType(data['parentComputes'], [SubComputeViewModel]);
            }
            if (data.hasOwnProperty('values')) {
                obj['values'] = ApiClient.convertToType(data['values'], [ComputeValueViewModel]);
            }
        }
        return obj;
    }

    /**
    * @member {String} guid
    */
    'guid' = undefined;
    /**
    * @member {String} key
    */
    'key' = undefined;
    /**
    * @member {String} formula
    */
    'formula' = undefined;
    /**
    * @member {Number} delay
    */
    'delay' = undefined;
    /**
    * @member {Number} failCount
    */
    'failCount' = undefined;
    /**
    * @member {Boolean} isEnabled
    */
    'isEnabled' = undefined;
    /**
    * @member {Array.<module:model/ComputeExpressionViewModel>} expressions
    */
    'expressions' = undefined;
    /**
    * @member {Array.<module:model/SubComputeViewModel>} childComputes
    */
    'childComputes' = undefined;
    /**
    * @member {Array.<module:model/SubComputeViewModel>} parentComputes
    */
    'parentComputes' = undefined;
    /**
    * @member {Array.<module:model/ComputeValueViewModel>} values
    */
    'values' = undefined;




}
