/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ComponentViewModel from './ComponentViewModel';

/**
* The ComponentViewModelIEnumerablePaginatedViewModel model module.
* @module model/ComponentViewModelIEnumerablePaginatedViewModel
* @version 5
*/
export default class ComponentViewModelIEnumerablePaginatedViewModel {
    /**
    * Constructs a new <code>ComponentViewModelIEnumerablePaginatedViewModel</code>.
    * @alias module:model/ComponentViewModelIEnumerablePaginatedViewModel
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ComponentViewModelIEnumerablePaginatedViewModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ComponentViewModelIEnumerablePaginatedViewModel} obj Optional instance to populate.
    * @return {module:model/ComponentViewModelIEnumerablePaginatedViewModel} The populated <code>ComponentViewModelIEnumerablePaginatedViewModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ComponentViewModelIEnumerablePaginatedViewModel();
                        
            
            if (data.hasOwnProperty('totalCount')) {
                obj['totalCount'] = ApiClient.convertToType(data['totalCount'], 'Number');
            }
            if (data.hasOwnProperty('payload')) {
                obj['payload'] = ApiClient.convertToType(data['payload'], [ComponentViewModel]);
            }
        }
        return obj;
    }

    /**
    * @member {Number} totalCount
    */
    'totalCount' = undefined;
    /**
    * @member {Array.<module:model/ComponentViewModel>} payload
    */
    'payload' = undefined;




}
