/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ComputeViewModel from './ComputeViewModel';

/**
* The ComputeValueViewModel model module.
* @module model/ComputeValueViewModel
* @version 5
*/
export default class ComputeValueViewModel {
    /**
    * Constructs a new <code>ComputeValueViewModel</code>.
    * @alias module:model/ComputeValueViewModel
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ComputeValueViewModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ComputeValueViewModel} obj Optional instance to populate.
    * @return {module:model/ComputeValueViewModel} The populated <code>ComputeValueViewModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ComputeValueViewModel();
                        
            
            if (data.hasOwnProperty('guid')) {
                obj['guid'] = ApiClient.convertToType(data['guid'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('computeGuid')) {
                obj['computeGuid'] = ApiClient.convertToType(data['computeGuid'], 'String');
            }
            if (data.hasOwnProperty('compute')) {
                obj['compute'] = ComputeViewModel.constructFromObject(data['compute']);
            }
            if (data.hasOwnProperty('isEnabled')) {
                obj['isEnabled'] = ApiClient.convertToType(data['isEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
        }
        return obj;
    }

    /**
    * @member {String} guid
    */
    'guid' = undefined;
    /**
    * @member {String} value
    */
    'value' = undefined;
    /**
    * @member {String} computeGuid
    */
    'computeGuid' = undefined;
    /**
    * @member {module:model/ComputeViewModel} compute
    */
    'compute' = undefined;
    /**
    * @member {Boolean} isEnabled
    */
    'isEnabled' = undefined;
    /**
    * @member {Date} createdAt
    */
    'createdAt' = undefined;




}
