/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ComponentHistoricItemViewModel from './ComponentHistoricItemViewModel';

/**
* The ComponentViewModel model module.
* @module model/ComponentViewModel
* @version 5
*/
export default class ComponentViewModel {
    /**
    * Constructs a new <code>ComponentViewModel</code>.
    * @alias module:model/ComponentViewModel
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ComponentViewModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ComponentViewModel} obj Optional instance to populate.
    * @return {module:model/ComponentViewModel} The populated <code>ComponentViewModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ComponentViewModel();
                        
            
            if (data.hasOwnProperty('guid')) {
                obj['guid'] = ApiClient.convertToType(data['guid'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'Number');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
            if (data.hasOwnProperty('query')) {
                obj['query'] = ApiClient.convertToType(data['query'], 'String');
            }
            if (data.hasOwnProperty('isDenominated')) {
                obj['isDenominated'] = ApiClient.convertToType(data['isDenominated'], 'Boolean');
            }
            if (data.hasOwnProperty('history')) {
                obj['history'] = ApiClient.convertToType(data['history'], [ComponentHistoricItemViewModel]);
            }
        }
        return obj;
    }

    /**
    * @member {String} guid
    */
    'guid' = undefined;
    /**
    * @member {Number} type
    */
    'type' = undefined;
    /**
    * @member {String} value
    */
    'value' = undefined;
    /**
    * @member {String} identifier
    */
    'identifier' = undefined;
    /**
    * @member {String} query
    */
    'query' = undefined;
    /**
    * @member {Boolean} isDenominated
    */
    'isDenominated' = undefined;
    /**
    * @member {Array.<module:model/ComponentHistoricItemViewModel>} history
    */
    'history' = undefined;




}
