/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ItemViewModel from './ItemViewModel';

/**
* The ItemPropertyViewModel model module.
* @module model/ItemPropertyViewModel
* @version 5
*/
export default class ItemPropertyViewModel {
    /**
    * Constructs a new <code>ItemPropertyViewModel</code>.
    * @alias module:model/ItemPropertyViewModel
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ItemPropertyViewModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ItemPropertyViewModel} obj Optional instance to populate.
    * @return {module:model/ItemPropertyViewModel} The populated <code>ItemPropertyViewModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ItemPropertyViewModel();
                        
            
            if (data.hasOwnProperty('guid')) {
                obj['guid'] = ApiClient.convertToType(data['guid'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('itemGuid')) {
                obj['itemGuid'] = ApiClient.convertToType(data['itemGuid'], 'String');
            }
            if (data.hasOwnProperty('item')) {
                obj['item'] = ItemViewModel.constructFromObject(data['item']);
            }
        }
        return obj;
    }

    /**
    * @member {String} guid
    */
    'guid' = undefined;
    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {String} value
    */
    'value' = undefined;
    /**
    * @member {String} itemGuid
    */
    'itemGuid' = undefined;
    /**
    * @member {module:model/ItemViewModel} item
    */
    'item' = undefined;




}
