/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ItemViewModel from './ItemViewModel';

/**
* The ItemViewModelIEnumerablePaginatedViewModel model module.
* @module model/ItemViewModelIEnumerablePaginatedViewModel
* @version 5
*/
export default class ItemViewModelIEnumerablePaginatedViewModel {
    /**
    * Constructs a new <code>ItemViewModelIEnumerablePaginatedViewModel</code>.
    * @alias module:model/ItemViewModelIEnumerablePaginatedViewModel
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ItemViewModelIEnumerablePaginatedViewModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ItemViewModelIEnumerablePaginatedViewModel} obj Optional instance to populate.
    * @return {module:model/ItemViewModelIEnumerablePaginatedViewModel} The populated <code>ItemViewModelIEnumerablePaginatedViewModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ItemViewModelIEnumerablePaginatedViewModel();
                        
            
            if (data.hasOwnProperty('totalCount')) {
                obj['totalCount'] = ApiClient.convertToType(data['totalCount'], 'Number');
            }
            if (data.hasOwnProperty('payload')) {
                obj['payload'] = ApiClient.convertToType(data['payload'], [ItemViewModel]);
            }
        }
        return obj;
    }

    /**
    * @member {Number} totalCount
    */
    'totalCount' = undefined;
    /**
    * @member {Array.<module:model/ItemViewModel>} payload
    */
    'payload' = undefined;




}
