/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ItemPropertyViewModel from './ItemPropertyViewModel';
import RequestViewModel from './RequestViewModel';
import TypeItemViewModel from './TypeItemViewModel';

/**
* The ItemViewModel model module.
* @module model/ItemViewModel
* @version 5
*/
export default class ItemViewModel {
    /**
    * Constructs a new <code>ItemViewModel</code>.
    * @alias module:model/ItemViewModel
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ItemViewModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ItemViewModel} obj Optional instance to populate.
    * @return {module:model/ItemViewModel} The populated <code>ItemViewModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ItemViewModel();
                        
            
            if (data.hasOwnProperty('guid')) {
                obj['guid'] = ApiClient.convertToType(data['guid'], 'String');
            }
            if (data.hasOwnProperty('logoPath')) {
                obj['logoPath'] = ApiClient.convertToType(data['logoPath'], 'String');
            }
            if (data.hasOwnProperty('abbreviation')) {
                obj['abbreviation'] = ApiClient.convertToType(data['abbreviation'], 'String');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('denominations')) {
                obj['denominations'] = ApiClient.convertToType(data['denominations'], 'Number');
            }
            if (data.hasOwnProperty('denominationName')) {
                obj['denominationName'] = ApiClient.convertToType(data['denominationName'], 'String');
            }
            if (data.hasOwnProperty('parentItemGuid')) {
                obj['parentItemGuid'] = ApiClient.convertToType(data['parentItemGuid'], 'String');
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], [ItemPropertyViewModel]);
            }
            if (data.hasOwnProperty('types')) {
                obj['types'] = ApiClient.convertToType(data['types'], [TypeItemViewModel]);
            }
            if (data.hasOwnProperty('requests')) {
                obj['requests'] = ApiClient.convertToType(data['requests'], [RequestViewModel]);
            }
        }
        return obj;
    }

    /**
    * @member {String} guid
    */
    'guid' = undefined;
    /**
    * @member {String} logoPath
    */
    'logoPath' = undefined;
    /**
    * @member {String} abbreviation
    */
    'abbreviation' = undefined;
    /**
    * @member {String} slug
    */
    'slug' = undefined;
    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {Number} denominations
    */
    'denominations' = undefined;
    /**
    * @member {String} denominationName
    */
    'denominationName' = undefined;
    /**
    * @member {String} parentItemGuid
    */
    'parentItemGuid' = undefined;
    /**
    * @member {Array.<module:model/ItemPropertyViewModel>} properties
    */
    'properties' = undefined;
    /**
    * @member {Array.<module:model/TypeItemViewModel>} types
    */
    'types' = undefined;
    /**
    * @member {Array.<module:model/RequestViewModel>} requests
    */
    'requests' = undefined;




}
