/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ComponentViewModel from './ComponentViewModel';
import ItemRequestViewModel from './ItemRequestViewModel';
import RequestPropertyViewModel from './RequestPropertyViewModel';
import WebsocketCommandViewModel from './WebsocketCommandViewModel';

/**
* The RequestViewModel model module.
* @module model/RequestViewModel
* @version 5
*/
export default class RequestViewModel {
    /**
    * Constructs a new <code>RequestViewModel</code>.
    * @alias module:model/RequestViewModel
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>RequestViewModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RequestViewModel} obj Optional instance to populate.
    * @return {module:model/RequestViewModel} The populated <code>RequestViewModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequestViewModel();
                        
            
            if (data.hasOwnProperty('guid')) {
                obj['guid'] = ApiClient.convertToType(data['guid'], 'String');
            }
            if (data.hasOwnProperty('requestType')) {
                obj['requestType'] = ApiClient.convertToType(data['requestType'], 'Number');
            }
            if (data.hasOwnProperty('responseType')) {
                obj['responseType'] = ApiClient.convertToType(data['responseType'], 'Number');
            }
            if (data.hasOwnProperty('endpoint')) {
                obj['endpoint'] = ApiClient.convertToType(data['endpoint'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('delay')) {
                obj['delay'] = ApiClient.convertToType(data['delay'], 'Number');
            }
            if (data.hasOwnProperty('failureDelay')) {
                obj['failureDelay'] = ApiClient.convertToType(data['failureDelay'], 'Number');
            }
            if (data.hasOwnProperty('isEnabled')) {
                obj['isEnabled'] = ApiClient.convertToType(data['isEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('components')) {
                obj['components'] = ApiClient.convertToType(data['components'], [ComponentViewModel]);
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [ItemRequestViewModel]);
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], [RequestPropertyViewModel]);
            }
            if (data.hasOwnProperty('websocketCommands')) {
                obj['websocketCommands'] = ApiClient.convertToType(data['websocketCommands'], [WebsocketCommandViewModel]);
            }
        }
        return obj;
    }

    /**
    * @member {String} guid
    */
    'guid' = undefined;
    /**
    * @member {Number} requestType
    */
    'requestType' = undefined;
    /**
    * @member {Number} responseType
    */
    'responseType' = undefined;
    /**
    * @member {String} endpoint
    */
    'endpoint' = undefined;
    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {Number} delay
    */
    'delay' = undefined;
    /**
    * @member {Number} failureDelay
    */
    'failureDelay' = undefined;
    /**
    * @member {Boolean} isEnabled
    */
    'isEnabled' = undefined;
    /**
    * @member {Array.<module:model/ComponentViewModel>} components
    */
    'components' = undefined;
    /**
    * @member {Array.<module:model/ItemRequestViewModel>} items
    */
    'items' = undefined;
    /**
    * @member {Array.<module:model/RequestPropertyViewModel>} properties
    */
    'properties' = undefined;
    /**
    * @member {Array.<module:model/WebsocketCommandViewModel>} websocketCommands
    */
    'websocketCommands' = undefined;




}
