/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ResponseType.
* @enum {}
* @readonly
*/
export default class ResponseType {
        /**
         * value: "Json"
         * @const
         */
        Json = "Json";

        /**
         * value: "XML"
         * @const
         */
        XML = "XML";

        /**
         * value: "Html"
         * @const
         */
        Html = "Html";

        /**
         * value: "JsonRpc"
         * @const
         */
        JsonRpc = "JsonRpc";


    /**
    * Returns a <code>ResponseType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ResponseType} The enum <code>ResponseType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}
