/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ItemViewModel from './ItemViewModel';
import TypeViewModel from './TypeViewModel';

/**
* The TypeItemViewModel model module.
* @module model/TypeItemViewModel
* @version 5
*/
export default class TypeItemViewModel {
    /**
    * Constructs a new <code>TypeItemViewModel</code>.
    * @alias module:model/TypeItemViewModel
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>TypeItemViewModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TypeItemViewModel} obj Optional instance to populate.
    * @return {module:model/TypeItemViewModel} The populated <code>TypeItemViewModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TypeItemViewModel();
                        
            
            if (data.hasOwnProperty('guid')) {
                obj['guid'] = ApiClient.convertToType(data['guid'], 'String');
            }
            if (data.hasOwnProperty('itemGuid')) {
                obj['itemGuid'] = ApiClient.convertToType(data['itemGuid'], 'String');
            }
            if (data.hasOwnProperty('item')) {
                obj['item'] = ItemViewModel.constructFromObject(data['item']);
            }
            if (data.hasOwnProperty('typeGuid')) {
                obj['typeGuid'] = ApiClient.convertToType(data['typeGuid'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = TypeViewModel.constructFromObject(data['type']);
            }
        }
        return obj;
    }

    /**
    * @member {String} guid
    */
    'guid' = undefined;
    /**
    * @member {String} itemGuid
    */
    'itemGuid' = undefined;
    /**
    * @member {module:model/ItemViewModel} item
    */
    'item' = undefined;
    /**
    * @member {String} typeGuid
    */
    'typeGuid' = undefined;
    /**
    * @member {module:model/TypeViewModel} type
    */
    'type' = undefined;




}
