/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RequestViewModel from './RequestViewModel';
import TypeItemViewModel from './TypeItemViewModel';

/**
* The TypeViewModel model module.
* @module model/TypeViewModel
* @version 5
*/
export default class TypeViewModel {
    /**
    * Constructs a new <code>TypeViewModel</code>.
    * @alias module:model/TypeViewModel
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>TypeViewModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TypeViewModel} obj Optional instance to populate.
    * @return {module:model/TypeViewModel} The populated <code>TypeViewModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TypeViewModel();
                        
            
            if (data.hasOwnProperty('guid')) {
                obj['guid'] = ApiClient.convertToType(data['guid'], 'String');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [TypeItemViewModel]);
            }
            if (data.hasOwnProperty('requests')) {
                obj['requests'] = ApiClient.convertToType(data['requests'], [RequestViewModel]);
            }
        }
        return obj;
    }

    /**
    * @member {String} guid
    */
    'guid' = undefined;
    /**
    * @member {String} slug
    */
    'slug' = undefined;
    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {Array.<module:model/TypeItemViewModel>} items
    */
    'items' = undefined;
    /**
    * @member {Array.<module:model/RequestViewModel>} requests
    */
    'requests' = undefined;




}
