/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ItemViewModel from './ItemViewModel';
import RequestViewModel from './RequestViewModel';

/**
* The UpdateItemRequestInputModel model module.
* @module model/UpdateItemRequestInputModel
* @version 5
*/
export default class UpdateItemRequestInputModel {
    /**
    * Constructs a new <code>UpdateItemRequestInputModel</code>.
    * @alias module:model/UpdateItemRequestInputModel
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UpdateItemRequestInputModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UpdateItemRequestInputModel} obj Optional instance to populate.
    * @return {module:model/UpdateItemRequestInputModel} The populated <code>UpdateItemRequestInputModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateItemRequestInputModel();
                        
            
            if (data.hasOwnProperty('guid')) {
                obj['guid'] = ApiClient.convertToType(data['guid'], 'String');
            }
            if (data.hasOwnProperty('requestId')) {
                obj['requestId'] = ApiClient.convertToType(data['requestId'], 'Number');
            }
            if (data.hasOwnProperty('request')) {
                obj['request'] = RequestViewModel.constructFromObject(data['request']);
            }
            if (data.hasOwnProperty('itemGuid')) {
                obj['itemGuid'] = ApiClient.convertToType(data['itemGuid'], 'String');
            }
            if (data.hasOwnProperty('item')) {
                obj['item'] = ItemViewModel.constructFromObject(data['item']);
            }
            if (data.hasOwnProperty('isEnabled')) {
                obj['isEnabled'] = ApiClient.convertToType(data['isEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('isDeleted')) {
                obj['isDeleted'] = ApiClient.convertToType(data['isDeleted'], 'Boolean');
            }
            if (data.hasOwnProperty('permanentDeletion')) {
                obj['permanentDeletion'] = ApiClient.convertToType(data['permanentDeletion'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {String} guid
    */
    'guid' = undefined;
    /**
    * @member {Number} requestId
    */
    'requestId' = undefined;
    /**
    * @member {module:model/RequestViewModel} request
    */
    'request' = undefined;
    /**
    * @member {String} itemGuid
    */
    'itemGuid' = undefined;
    /**
    * @member {module:model/ItemViewModel} item
    */
    'item' = undefined;
    /**
    * @member {Boolean} isEnabled
    */
    'isEnabled' = undefined;
    /**
    * @member {Boolean} isDeleted
    */
    'isDeleted' = undefined;
    /**
    * @member {Boolean} permanentDeletion
    */
    'permanentDeletion' = undefined;




}
