/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The UpdateComponentHistoricItemInputModel model module.
* @module model/UpdateComponentHistoricItemInputModel
* @version 5
*/
export default class UpdateComponentHistoricItemInputModel {
    /**
    * Constructs a new <code>UpdateComponentHistoricItemInputModel</code>.
    * @alias module:model/UpdateComponentHistoricItemInputModel
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UpdateComponentHistoricItemInputModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UpdateComponentHistoricItemInputModel} obj Optional instance to populate.
    * @return {module:model/UpdateComponentHistoricItemInputModel} The populated <code>UpdateComponentHistoricItemInputModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateComponentHistoricItemInputModel();
                        
            
            if (data.hasOwnProperty('guid')) {
                obj['guid'] = ApiClient.convertToType(data['guid'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} guid
    */
    'guid' = undefined;
    /**
    * @member {Date} timestamp
    */
    'timestamp' = undefined;
    /**
    * @member {String} value
    */
    'value' = undefined;




}
