/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RequestPropertyType from './RequestPropertyType';

/**
* The UpdateRequestPropertyInputModel model module.
* @module model/UpdateRequestPropertyInputModel
* @version 5
*/
export default class UpdateRequestPropertyInputModel {
    /**
    * Constructs a new <code>UpdateRequestPropertyInputModel</code>.
    * @alias module:model/UpdateRequestPropertyInputModel
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UpdateRequestPropertyInputModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UpdateRequestPropertyInputModel} obj Optional instance to populate.
    * @return {module:model/UpdateRequestPropertyInputModel} The populated <code>UpdateRequestPropertyInputModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateRequestPropertyInputModel();
                        
            
            if (data.hasOwnProperty('guid')) {
                obj['guid'] = ApiClient.convertToType(data['guid'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = RequestPropertyType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('isEnabled')) {
                obj['isEnabled'] = ApiClient.convertToType(data['isEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('requestGuid')) {
                obj['requestGuid'] = ApiClient.convertToType(data['requestGuid'], 'String');
            }
            if (data.hasOwnProperty('isDeleted')) {
                obj['isDeleted'] = ApiClient.convertToType(data['isDeleted'], 'Boolean');
            }
            if (data.hasOwnProperty('permanentDeletion')) {
                obj['permanentDeletion'] = ApiClient.convertToType(data['permanentDeletion'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {String} guid
    */
    'guid' = undefined;
    /**
    * @member {module:model/RequestPropertyType} type
    */
    'type' = undefined;
    /**
    * @member {String} key
    */
    'key' = undefined;
    /**
    * @member {String} value
    */
    'value' = undefined;
    /**
    * @member {Boolean} isEnabled
    */
    'isEnabled' = undefined;
    /**
    * @member {String} requestGuid
    */
    'requestGuid' = undefined;
    /**
    * @member {Boolean} isDeleted
    */
    'isDeleted' = undefined;
    /**
    * @member {Boolean} permanentDeletion
    */
    'permanentDeletion' = undefined;




}
