/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RequestViewModel from './RequestViewModel';
import TypeViewModel from './TypeViewModel';

/**
* The UpdateTypeRequestInputModel model module.
* @module model/UpdateTypeRequestInputModel
* @version 5
*/
export default class UpdateTypeRequestInputModel {
    /**
    * Constructs a new <code>UpdateTypeRequestInputModel</code>.
    * @alias module:model/UpdateTypeRequestInputModel
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UpdateTypeRequestInputModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UpdateTypeRequestInputModel} obj Optional instance to populate.
    * @return {module:model/UpdateTypeRequestInputModel} The populated <code>UpdateTypeRequestInputModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateTypeRequestInputModel();
                        
            
            if (data.hasOwnProperty('guid')) {
                obj['guid'] = ApiClient.convertToType(data['guid'], 'String');
            }
            if (data.hasOwnProperty('typeGuid')) {
                obj['typeGuid'] = ApiClient.convertToType(data['typeGuid'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = TypeViewModel.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('requestId')) {
                obj['requestId'] = ApiClient.convertToType(data['requestId'], 'Number');
            }
            if (data.hasOwnProperty('request')) {
                obj['request'] = RequestViewModel.constructFromObject(data['request']);
            }
            if (data.hasOwnProperty('isDeleted')) {
                obj['isDeleted'] = ApiClient.convertToType(data['isDeleted'], 'Boolean');
            }
            if (data.hasOwnProperty('permanentDeletion')) {
                obj['permanentDeletion'] = ApiClient.convertToType(data['permanentDeletion'], 'Boolean');
            }
            if (data.hasOwnProperty('isEnabled')) {
                obj['isEnabled'] = ApiClient.convertToType(data['isEnabled'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {String} guid
    */
    'guid' = undefined;
    /**
    * @member {String} typeGuid
    */
    'typeGuid' = undefined;
    /**
    * @member {module:model/TypeViewModel} type
    */
    'type' = undefined;
    /**
    * @member {Number} requestId
    */
    'requestId' = undefined;
    /**
    * @member {module:model/RequestViewModel} request
    */
    'request' = undefined;
    /**
    * @member {Boolean} isDeleted
    */
    'isDeleted' = undefined;
    /**
    * @member {Boolean} permanentDeletion
    */
    'permanentDeletion' = undefined;
    /**
    * @member {Boolean} isEnabled
    */
    'isEnabled' = undefined;




}
