/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ItemViewModel from './ItemViewModel';
import TypeViewModel from './TypeViewModel';

/**
* The UpdateTypeItemInputModel model module.
* @module model/UpdateTypeItemInputModel
* @version 5
*/
export default class UpdateTypeItemInputModel {
    /**
    * Constructs a new <code>UpdateTypeItemInputModel</code>.
    * @alias module:model/UpdateTypeItemInputModel
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UpdateTypeItemInputModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UpdateTypeItemInputModel} obj Optional instance to populate.
    * @return {module:model/UpdateTypeItemInputModel} The populated <code>UpdateTypeItemInputModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateTypeItemInputModel();
                        
            
            if (data.hasOwnProperty('guid')) {
                obj['guid'] = ApiClient.convertToType(data['guid'], 'String');
            }
            if (data.hasOwnProperty('typeGuid')) {
                obj['typeGuid'] = ApiClient.convertToType(data['typeGuid'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = TypeViewModel.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('itemGuid')) {
                obj['itemGuid'] = ApiClient.convertToType(data['itemGuid'], 'String');
            }
            if (data.hasOwnProperty('item')) {
                obj['item'] = ItemViewModel.constructFromObject(data['item']);
            }
            if (data.hasOwnProperty('isEnabled')) {
                obj['isEnabled'] = ApiClient.convertToType(data['isEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('isDeleted')) {
                obj['isDeleted'] = ApiClient.convertToType(data['isDeleted'], 'Boolean');
            }
            if (data.hasOwnProperty('permanentDeletion')) {
                obj['permanentDeletion'] = ApiClient.convertToType(data['permanentDeletion'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {String} guid
    */
    'guid' = undefined;
    /**
    * @member {String} typeGuid
    */
    'typeGuid' = undefined;
    /**
    * @member {module:model/TypeViewModel} type
    */
    'type' = undefined;
    /**
    * @member {String} itemGuid
    */
    'itemGuid' = undefined;
    /**
    * @member {module:model/ItemViewModel} item
    */
    'item' = undefined;
    /**
    * @member {Boolean} isEnabled
    */
    'isEnabled' = undefined;
    /**
    * @member {Boolean} isDeleted
    */
    'isDeleted' = undefined;
    /**
    * @member {Boolean} permanentDeletion
    */
    'permanentDeletion' = undefined;




}
