/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RequestType from './RequestType';
import ResponseType from './ResponseType';
import UpdateComponentInputModel from './UpdateComponentInputModel';
import UpdateItemRequestInputModel from './UpdateItemRequestInputModel';
import UpdateRequestPropertyInputModel from './UpdateRequestPropertyInputModel';
import UpdateTypeRequestInputModel from './UpdateTypeRequestInputModel';
import UpdateWebsocketCommandInputModel from './UpdateWebsocketCommandInputModel';

/**
* The UpdateRequestInputModel model module.
* @module model/UpdateRequestInputModel
* @version 5
*/
export default class UpdateRequestInputModel {
    /**
    * Constructs a new <code>UpdateRequestInputModel</code>.
    * @alias module:model/UpdateRequestInputModel
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UpdateRequestInputModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UpdateRequestInputModel} obj Optional instance to populate.
    * @return {module:model/UpdateRequestInputModel} The populated <code>UpdateRequestInputModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateRequestInputModel();
                        
            
            if (data.hasOwnProperty('guid')) {
                obj['guid'] = ApiClient.convertToType(data['guid'], 'String');
            }
            if (data.hasOwnProperty('requestType')) {
                obj['requestType'] = RequestType.constructFromObject(data['requestType']);
            }
            if (data.hasOwnProperty('responseType')) {
                obj['responseType'] = ResponseType.constructFromObject(data['responseType']);
            }
            if (data.hasOwnProperty('endpoint')) {
                obj['endpoint'] = ApiClient.convertToType(data['endpoint'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('delay')) {
                obj['delay'] = ApiClient.convertToType(data['delay'], 'Number');
            }
            if (data.hasOwnProperty('failureDelay')) {
                obj['failureDelay'] = ApiClient.convertToType(data['failureDelay'], 'Number');
            }
            if (data.hasOwnProperty('isEnabled')) {
                obj['isEnabled'] = ApiClient.convertToType(data['isEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('types')) {
                obj['types'] = ApiClient.convertToType(data['types'], [UpdateTypeRequestInputModel]);
            }
            if (data.hasOwnProperty('components')) {
                obj['components'] = ApiClient.convertToType(data['components'], [UpdateComponentInputModel]);
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [UpdateItemRequestInputModel]);
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], [UpdateRequestPropertyInputModel]);
            }
            if (data.hasOwnProperty('websocketCommands')) {
                obj['websocketCommands'] = ApiClient.convertToType(data['websocketCommands'], [UpdateWebsocketCommandInputModel]);
            }
        }
        return obj;
    }

    /**
    * @member {String} guid
    */
    'guid' = undefined;
    /**
    * @member {module:model/RequestType} requestType
    */
    'requestType' = undefined;
    /**
    * @member {module:model/ResponseType} responseType
    */
    'responseType' = undefined;
    /**
    * @member {String} endpoint
    */
    'endpoint' = undefined;
    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {Number} delay
    */
    'delay' = undefined;
    /**
    * @member {Number} failureDelay
    */
    'failureDelay' = undefined;
    /**
    * @member {Boolean} isEnabled
    */
    'isEnabled' = undefined;
    /**
    * @member {Array.<module:model/UpdateTypeRequestInputModel>} types
    */
    'types' = undefined;
    /**
    * @member {Array.<module:model/UpdateComponentInputModel>} components
    */
    'components' = undefined;
    /**
    * @member {Array.<module:model/UpdateItemRequestInputModel>} items
    */
    'items' = undefined;
    /**
    * @member {Array.<module:model/UpdateRequestPropertyInputModel>} properties
    */
    'properties' = undefined;
    /**
    * @member {Array.<module:model/UpdateWebsocketCommandInputModel>} websocketCommands
    */
    'websocketCommands' = undefined;




}
