/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import ComponentHistoricItemViewModelIEnumerablePaginatedViewModel from '../model/ComponentHistoricItemViewModelIEnumerablePaginatedViewModel';

/**
* ComponentHistoricItem service.
* @module api/ComponentHistoricItemApi
* @version 5
*/
export default class ComponentHistoricItemApi {

    /**
    * Constructs a new ComponentHistoricItemApi. 
    * @alias module:api/ComponentHistoricItemApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the componentHistoricItemAllComponentGuidGet operation.
     * @callback module:api/ComponentHistoricItemApi~componentHistoricItemAllComponentGuidGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ComponentHistoricItemViewModelIEnumerablePaginatedViewModel} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Obtain all the component historical values created
     * @param {Object} opts Optional parameters
     * @param {module:api/ComponentHistoricItemApi~componentHistoricItemAllComponentGuidGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ComponentHistoricItemViewModelIEnumerablePaginatedViewModel}
     */
    componentHistoricItemAllComponentGuidGet(componentGuid, opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        'componentGuid': componentGuid
      };
      let queryParams = {
        'index': opts['index']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['API Key'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = ComponentHistoricItemViewModelIEnumerablePaginatedViewModel;

      return this.apiClient.callApi(
        '/ComponentHistoricItem/All/{componentGuid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
