/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import ComponentTypeViewModelIEnumerablePaginatedViewModel from '../model/ComponentTypeViewModelIEnumerablePaginatedViewModel';

/**
* ComponentType service.
* @module api/ComponentTypeApi
* @version 5
*/
export default class ComponentTypeApi {

    /**
    * Constructs a new ComponentTypeApi. 
    * @alias module:api/ComponentTypeApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the componentTypeAllGet operation.
     * @callback module:api/ComponentTypeApi~componentTypeAllGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ComponentTypeViewModelIEnumerablePaginatedViewModel} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Obtain all of the component types that are publicly available or the ones that you own.
     * @param {Object} opts Optional parameters
     * @param {module:api/ComponentTypeApi~componentTypeAllGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ComponentTypeViewModelIEnumerablePaginatedViewModel}
     */
    componentTypeAllGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'index': opts['index']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['API Key'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = ComponentTypeViewModelIEnumerablePaginatedViewModel;

      return this.apiClient.callApi(
        '/ComponentType/All', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
