/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NozomiApi);
  }
}(this, function(expect, NozomiApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NozomiApi.ComputeValueViewModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ComputeValueViewModel', function() {
    it('should create an instance of ComputeValueViewModel', function() {
      // uncomment below and update the code to test ComputeValueViewModel
      //var instane = new NozomiApi.ComputeValueViewModel();
      //expect(instance).to.be.a(NozomiApi.ComputeValueViewModel);
    });

    it('should have the property guid (base name: "guid")', function() {
      // uncomment below and update the code to test the property guid
      //var instane = new NozomiApi.ComputeValueViewModel();
      //expect(instance).to.be();
    });

    it('should have the property value (base name: "value")', function() {
      // uncomment below and update the code to test the property value
      //var instane = new NozomiApi.ComputeValueViewModel();
      //expect(instance).to.be();
    });

    it('should have the property computeGuid (base name: "computeGuid")', function() {
      // uncomment below and update the code to test the property computeGuid
      //var instane = new NozomiApi.ComputeValueViewModel();
      //expect(instance).to.be();
    });

    it('should have the property compute (base name: "compute")', function() {
      // uncomment below and update the code to test the property compute
      //var instane = new NozomiApi.ComputeValueViewModel();
      //expect(instance).to.be();
    });

    it('should have the property isEnabled (base name: "isEnabled")', function() {
      // uncomment below and update the code to test the property isEnabled
      //var instane = new NozomiApi.ComputeValueViewModel();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new NozomiApi.ComputeValueViewModel();
      //expect(instance).to.be();
    });

  });

}));
