/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NozomiApi);
  }
}(this, function(expect, NozomiApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NozomiApi.ItemViewModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ItemViewModel', function() {
    it('should create an instance of ItemViewModel', function() {
      // uncomment below and update the code to test ItemViewModel
      //var instane = new NozomiApi.ItemViewModel();
      //expect(instance).to.be.a(NozomiApi.ItemViewModel);
    });

    it('should have the property guid (base name: "guid")', function() {
      // uncomment below and update the code to test the property guid
      //var instane = new NozomiApi.ItemViewModel();
      //expect(instance).to.be();
    });

    it('should have the property logoPath (base name: "logoPath")', function() {
      // uncomment below and update the code to test the property logoPath
      //var instane = new NozomiApi.ItemViewModel();
      //expect(instance).to.be();
    });

    it('should have the property abbreviation (base name: "abbreviation")', function() {
      // uncomment below and update the code to test the property abbreviation
      //var instane = new NozomiApi.ItemViewModel();
      //expect(instance).to.be();
    });

    it('should have the property slug (base name: "slug")', function() {
      // uncomment below and update the code to test the property slug
      //var instane = new NozomiApi.ItemViewModel();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new NozomiApi.ItemViewModel();
      //expect(instance).to.be();
    });

    it('should have the property denominations (base name: "denominations")', function() {
      // uncomment below and update the code to test the property denominations
      //var instane = new NozomiApi.ItemViewModel();
      //expect(instance).to.be();
    });

    it('should have the property denominationName (base name: "denominationName")', function() {
      // uncomment below and update the code to test the property denominationName
      //var instane = new NozomiApi.ItemViewModel();
      //expect(instance).to.be();
    });

    it('should have the property parentItemGuid (base name: "parentItemGuid")', function() {
      // uncomment below and update the code to test the property parentItemGuid
      //var instane = new NozomiApi.ItemViewModel();
      //expect(instance).to.be();
    });

    it('should have the property properties (base name: "properties")', function() {
      // uncomment below and update the code to test the property properties
      //var instane = new NozomiApi.ItemViewModel();
      //expect(instance).to.be();
    });

    it('should have the property types (base name: "types")', function() {
      // uncomment below and update the code to test the property types
      //var instane = new NozomiApi.ItemViewModel();
      //expect(instance).to.be();
    });

    it('should have the property requests (base name: "requests")', function() {
      // uncomment below and update the code to test the property requests
      //var instane = new NozomiApi.ItemViewModel();
      //expect(instance).to.be();
    });

  });

}));
