/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NozomiApi);
  }
}(this, function(expect, NozomiApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NozomiApi.SubComputeViewModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SubComputeViewModel', function() {
    it('should create an instance of SubComputeViewModel', function() {
      // uncomment below and update the code to test SubComputeViewModel
      //var instane = new NozomiApi.SubComputeViewModel();
      //expect(instance).to.be.a(NozomiApi.SubComputeViewModel);
    });

    it('should have the property parentComputeGuid (base name: "parentComputeGuid")', function() {
      // uncomment below and update the code to test the property parentComputeGuid
      //var instane = new NozomiApi.SubComputeViewModel();
      //expect(instance).to.be();
    });

    it('should have the property parentCompute (base name: "parentCompute")', function() {
      // uncomment below and update the code to test the property parentCompute
      //var instane = new NozomiApi.SubComputeViewModel();
      //expect(instance).to.be();
    });

    it('should have the property childComputeGuid (base name: "childComputeGuid")', function() {
      // uncomment below and update the code to test the property childComputeGuid
      //var instane = new NozomiApi.SubComputeViewModel();
      //expect(instance).to.be();
    });

    it('should have the property childCompute (base name: "childCompute")', function() {
      // uncomment below and update the code to test the property childCompute
      //var instane = new NozomiApi.SubComputeViewModel();
      //expect(instance).to.be();
    });

    it('should have the property isEnabled (base name: "isEnabled")', function() {
      // uncomment below and update the code to test the property isEnabled
      //var instane = new NozomiApi.SubComputeViewModel();
      //expect(instance).to.be();
    });

  });

}));
