/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NozomiApi);
  }
}(this, function(expect, NozomiApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NozomiApi.UpdateTypeRequestInputModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UpdateTypeRequestInputModel', function() {
    it('should create an instance of UpdateTypeRequestInputModel', function() {
      // uncomment below and update the code to test UpdateTypeRequestInputModel
      //var instane = new NozomiApi.UpdateTypeRequestInputModel();
      //expect(instance).to.be.a(NozomiApi.UpdateTypeRequestInputModel);
    });

    it('should have the property guid (base name: "guid")', function() {
      // uncomment below and update the code to test the property guid
      //var instane = new NozomiApi.UpdateTypeRequestInputModel();
      //expect(instance).to.be();
    });

    it('should have the property typeGuid (base name: "typeGuid")', function() {
      // uncomment below and update the code to test the property typeGuid
      //var instane = new NozomiApi.UpdateTypeRequestInputModel();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new NozomiApi.UpdateTypeRequestInputModel();
      //expect(instance).to.be();
    });

    it('should have the property requestId (base name: "requestId")', function() {
      // uncomment below and update the code to test the property requestId
      //var instane = new NozomiApi.UpdateTypeRequestInputModel();
      //expect(instance).to.be();
    });

    it('should have the property request (base name: "request")', function() {
      // uncomment below and update the code to test the property request
      //var instane = new NozomiApi.UpdateTypeRequestInputModel();
      //expect(instance).to.be();
    });

    it('should have the property isDeleted (base name: "isDeleted")', function() {
      // uncomment below and update the code to test the property isDeleted
      //var instane = new NozomiApi.UpdateTypeRequestInputModel();
      //expect(instance).to.be();
    });

    it('should have the property permanentDeletion (base name: "permanentDeletion")', function() {
      // uncomment below and update the code to test the property permanentDeletion
      //var instane = new NozomiApi.UpdateTypeRequestInputModel();
      //expect(instance).to.be();
    });

    it('should have the property isEnabled (base name: "isEnabled")', function() {
      // uncomment below and update the code to test the property isEnabled
      //var instane = new NozomiApi.UpdateTypeRequestInputModel();
      //expect(instance).to.be();
    });

  });

}));
