/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NozomiApi);
  }
}(this, function(expect, NozomiApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NozomiApi.UpdateRequestInputModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UpdateRequestInputModel', function() {
    it('should create an instance of UpdateRequestInputModel', function() {
      // uncomment below and update the code to test UpdateRequestInputModel
      //var instane = new NozomiApi.UpdateRequestInputModel();
      //expect(instance).to.be.a(NozomiApi.UpdateRequestInputModel);
    });

    it('should have the property guid (base name: "guid")', function() {
      // uncomment below and update the code to test the property guid
      //var instane = new NozomiApi.UpdateRequestInputModel();
      //expect(instance).to.be();
    });

    it('should have the property requestType (base name: "requestType")', function() {
      // uncomment below and update the code to test the property requestType
      //var instane = new NozomiApi.UpdateRequestInputModel();
      //expect(instance).to.be();
    });

    it('should have the property responseType (base name: "responseType")', function() {
      // uncomment below and update the code to test the property responseType
      //var instane = new NozomiApi.UpdateRequestInputModel();
      //expect(instance).to.be();
    });

    it('should have the property endpoint (base name: "endpoint")', function() {
      // uncomment below and update the code to test the property endpoint
      //var instane = new NozomiApi.UpdateRequestInputModel();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new NozomiApi.UpdateRequestInputModel();
      //expect(instance).to.be();
    });

    it('should have the property delay (base name: "delay")', function() {
      // uncomment below and update the code to test the property delay
      //var instane = new NozomiApi.UpdateRequestInputModel();
      //expect(instance).to.be();
    });

    it('should have the property failureDelay (base name: "failureDelay")', function() {
      // uncomment below and update the code to test the property failureDelay
      //var instane = new NozomiApi.UpdateRequestInputModel();
      //expect(instance).to.be();
    });

    it('should have the property isEnabled (base name: "isEnabled")', function() {
      // uncomment below and update the code to test the property isEnabled
      //var instane = new NozomiApi.UpdateRequestInputModel();
      //expect(instance).to.be();
    });

    it('should have the property types (base name: "types")', function() {
      // uncomment below and update the code to test the property types
      //var instane = new NozomiApi.UpdateRequestInputModel();
      //expect(instance).to.be();
    });

    it('should have the property components (base name: "components")', function() {
      // uncomment below and update the code to test the property components
      //var instane = new NozomiApi.UpdateRequestInputModel();
      //expect(instance).to.be();
    });

    it('should have the property items (base name: "items")', function() {
      // uncomment below and update the code to test the property items
      //var instane = new NozomiApi.UpdateRequestInputModel();
      //expect(instance).to.be();
    });

    it('should have the property properties (base name: "properties")', function() {
      // uncomment below and update the code to test the property properties
      //var instane = new NozomiApi.UpdateRequestInputModel();
      //expect(instance).to.be();
    });

    it('should have the property websocketCommands (base name: "websocketCommands")', function() {
      // uncomment below and update the code to test the property websocketCommands
      //var instane = new NozomiApi.UpdateRequestInputModel();
      //expect(instance).to.be();
    });

  });

}));
