/**
 * Nozomi API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NozomiApi);
  }
}(this, function(expect, NozomiApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NozomiApi.ItemApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ItemApi', function() {
    describe('itemAllIndexGet', function() {
      it('should call itemAllIndexGet successfully', function(done) {
        //uncomment below and update the code to test itemAllIndexGet
        //instance.itemAllIndexGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('itemCreatePost', function() {
      it('should call itemCreatePost successfully', function(done) {
        //uncomment below and update the code to test itemCreatePost
        //instance.itemCreatePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('itemExistsSlugGet', function() {
      it('should call itemExistsSlugGet successfully', function(done) {
        //uncomment below and update the code to test itemExistsSlugGet
        //instance.itemExistsSlugGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('itemGetBySlugSlugGet', function() {
      it('should call itemGetBySlugSlugGet successfully', function(done) {
        //uncomment below and update the code to test itemGetBySlugSlugGet
        //instance.itemGetBySlugSlugGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('itemGetItemGuidGet', function() {
      it('should call itemGetItemGuidGet successfully', function(done) {
        //uncomment below and update the code to test itemGetItemGuidGet
        //instance.itemGetItemGuidGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('itemUpdatePut', function() {
      it('should call itemUpdatePut successfully', function(done) {
        //uncomment below and update the code to test itemUpdatePut
        //instance.itemUpdatePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
